#kivy 2.1
<TopTabbedPanel>
    do_default_tab: False
    tab_height: 30
    tab_width: 120
    background_color: 0.16, 0.2, 0.24
    TabbedPanelItem:
        text: "Szimulátor"
        SimTabLayout:
            id: sim_layout
    TabbedPanelItem:
        text: "Beállítások"
        SettingsTabLayout:
            id: settings_layout
    TabbedPanelItem:
        text: "Paradigma"
        ParadigmTabLayout:
            id: para_layout
    TabbedPanelItem:
        text: "Multiszim"
