name: continuous-integration

on: [push]

jobs:
  lint_and_test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        pip install -r requirements.txt
    - name: Lint with ruff
      uses: ChartBoost/ruff-action@v1
      with:
        args: --format=github --ignore=E402,E501 .
    - name: Test with pytest
      run: |
        pytest -x
